//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranTuanKiet_2119110248.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int id { get; set; }
        public string Introduct { get; set; }
        public string policy { get; set; }
        public string img { get; set; }
    }
}
