//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranTuanKiet_2119110248.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [Display(Name = "Mã đơn hàng")]
        public int Id { get; set; }
        [Display(Name = "Tên đơn hàng")]
        public string Name { get; set; }
        [Display(Name = "Mã Khách hàng")]
        public Nullable<int> UserId { get; set; }
      
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        [Display(Name = "Trạng Thái đơn hàng")]
        public Nullable<int> Status { get; set; }
     
        public string ProducName { get; set; }
        public Nullable<double> price { get; set; }
    }
}
