//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranTuanKiet_2119110248.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int SlideID { get; set; }
        public string Avatar { get; set; }
        public string Name { get; set; }
        public Nullable<int> Show { get; set; }
    }
}
