//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranTuanKiet_2119110248
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public int BranID { get; set; }
        public string BrandName { get; set; }
        public string Avatar { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
